export { createCacheHandler } from "./legacy-handler";
export type {
  AnyRedisClient,
  CacheEvent,
  CircuitBreakerOptions,
  ClientSource,
  Compression,
  FallbackOptions,
  HandlerName,
  LegacyCacheHandlerClass,
  LegacyCacheHandlerInstance,
  LegacyCacheValue,
  LegacyGetContext,
  LegacyHandlerContext,
  LegacySetContext,
  Logger,
  LogLevel,
  RedisCacheConfig,
  TimeoutOptions,
  TtlOptions,
} from "./types";
